// <auto-generated />
using System;
using System.Collections.Generic;
using LogicParser.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogicParser.Api.Migrations
{
    [DbContext(typeof(LogicParserContext))]
    [Migration("20260502015555_DeleteUnneededRows")]
    partial class DeleteUnneededRows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogicParser.Api.Entities.SolveLogicSave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Result")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Variables")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Saves");
                });

            modelBuilder.Entity("LogicParser.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LogicParser.Api.SideEntities.KnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Knowledge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SolveLogicSaveId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SolveLogicSaveId");

                    b.ToTable("KnowledgeBase");
                });

            modelBuilder.Entity("LogicParser.Api.SideEntities.KnowledgeBase", b =>
                {
                    b.HasOne("LogicParser.Api.Entities.SolveLogicSave", null)
                        .WithMany("Clauses")
                        .HasForeignKey("SolveLogicSaveId");
                });

            modelBuilder.Entity("LogicParser.Api.Entities.SolveLogicSave", b =>
                {
                    b.Navigation("Clauses");
                });
#pragma warning restore 612, 618
        }
    }
}
